wandb_version: 1

alpha:
  value: 4.830036820839838
batch-size:
  value: 4
features:
  value: 16
lr:
  value: 2.5979893199967307e-05
out_channels:
  value: 4
patience:
  value: 50
size:
  value: 128
vesselnet:
  value: false
