wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    mask/class_labels:
      predictions_wandb_delimeter_ground truth:
        key: predictions_wandb_delimeter_ground truth
        type: mask/class_labels
        value:
          '0': class_0
      predictions_wandb_delimeter_prediction:
        key: predictions_wandb_delimeter_prediction
        type: mask/class_labels
        value:
          '0': class_0
    python_version: 3.8.5
    start_time: 1642151542
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.8.5
      5: 0.12.9
      8:
      - 5
