wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Average number of detected_points
      5: 1
      6:
      - 1
    - 1: Normalized_val_loss
      5: 1
      6:
      - 1
    - 1: Precision
      5: 1
      6:
      - 1
    - 1: Recall
      5: 1
      6:
      - 1
    - 1: F1 score
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: predictions._type
      5: 1
      6:
      - 1
    - 1: predictions.path
      5: 1
      6:
      - 1
    - 1: predictions.sha256
      5: 1
      6:
      - 1
    - 1: predictions.size
      5: 1
      6:
      - 1
    - 1: predictions.format
      5: 1
      6:
      - 1
    - 1: predictions.width
      5: 1
      6:
      - 1
    - 1: predictions.height
      5: 1
      6:
      - 1
    - 1: pred_mask._type
      5: 1
      6:
      - 1
    - 1: pred_mask.path
      5: 1
      6:
      - 1
    - 1: pred_mask.sha256
      5: 1
      6:
      - 1
    - 1: pred_mask.size
      5: 1
      6:
      - 1
    - 1: pred_mask.format
      5: 1
      6:
      - 1
    - 1: pred_mask.width
      5: 1
      6:
      - 1
    - 1: pred_mask.height
      5: 1
      6:
      - 1
    - 1: true_mask._type
      5: 1
      6:
      - 1
    - 1: true_mask.path
      5: 1
      6:
      - 1
    - 1: true_mask.sha256
      5: 1
      6:
      - 1
    - 1: true_mask.size
      5: 1
      6:
      - 1
    - 1: true_mask.format
      5: 1
      6:
      - 1
    - 1: true_mask.width
      5: 1
      6:
      - 1
    - 1: true_mask.height
      5: 1
      6:
      - 1
    - 1: lr-Adam
      5: 1
      6:
      - 1
    python_version: 3.8.5
    start_time: 1642673727
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.8.5
      5: 0.12.9
      8:
      - 5
