wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1685460193.08201
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 37
      4: 3.10.4
      5: 0.13.3
      8:
      - 5
alpha:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 10
data:
  desc: null
  value: IOSTAR
device:
  desc: null
  value: 1
epochs:
  desc: null
  value: 2
features:
  desc: null
  value: 8
lr:
  desc: null
  value: 3.85680367447801e-05
no_endpoints:
  desc: null
  value: false
out_channels:
  desc: null
  value: 4
patience:
  desc: null
  value: 100
second_unet:
  desc: null
  value: false
size:
  desc: null
  value: 64
threshold:
  desc: null
  value: 0.05
vesselnet:
  desc: null
  value: false
weights:
  desc: null
  value: ./weights/
workers:
  desc: null
  value: 16
