wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: predictions._type
      5: 1
      6:
      - 1
    - 1: predictions.width
      5: 1
      6:
      - 1
    - 1: predictions.height
      5: 1
      6:
      - 1
    - 1: predictions.format
      5: 1
      6:
      - 1
    - 1: predictions.count
      5: 1
      6:
      - 1
    - 1: predictions.all_masks
      5: 1
      6:
      - 1
    mask/class_labels:
      predictions_wandb_delimeter_ground truth:
        key: predictions_wandb_delimeter_ground truth
        type: mask/class_labels
        value:
          '0': class_0
          '1': class_1
      predictions_wandb_delimeter_prediction:
        key: predictions_wandb_delimeter_prediction
        type: mask/class_labels
        value:
          '0': class_0
    python_version: 3.8.5
    start_time: 1642154012
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.8.5
      5: 0.12.9
      8:
      - 5
