wandb_version: 1

alpha:
  value: 1.410555916267663
batch-size:
  value: 4
features:
  value: 32
lr:
  value: 0.0008404147654661975
out_channels:
  value: 3
patience:
  value: 400
size:
  value: 512
vesselnet:
  value: false
