wandb_version: 1

alpha:
  value: 6.751932095680124
batch-size:
  value: 4
features:
  value: 64
lr:
  value: 5.569643145510482e-05
out_channels:
  value: 3
patience:
  value: 100
size:
  value: 128
vesselnet:
  value: false
