wandb_version: 1

alpha:
  value: 3.2672774479324955
batch-size:
  value: 16
features:
  value: 32
lr:
  value: 0.00011328084965697988
out_channels:
  value: 4
patience:
  value: 50
size:
  value: 256
vesselnet:
  value: false
