wandb_version: 1

alpha:
  value: 6.013615292268103
batch-size:
  value: 8
features:
  value: 16
lr:
  value: 4.932712453055365e-05
out_channels:
  value: 3
patience:
  value: 50
size:
  value: 512
vesselnet:
  value: false
