wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: Background._type
      5: 1
      6:
      - 1
    - 1: Background.path
      5: 1
      6:
      - 1
    - 1: Background.sha256
      5: 1
      6:
      - 1
    - 1: Background.size
      5: 1
      6:
      - 1
    - 1: Background.format
      5: 1
      6:
      - 1
    - 1: Background.width
      5: 1
      6:
      - 1
    - 1: Background.height
      5: 1
      6:
      - 1
    - 1: predicted._type
      5: 1
      6:
      - 1
    - 1: predicted.path
      5: 1
      6:
      - 1
    - 1: predicted.sha256
      5: 1
      6:
      - 1
    - 1: predicted.size
      5: 1
      6:
      - 1
    - 1: predicted.format
      5: 1
      6:
      - 1
    - 1: predicted.width
      5: 1
      6:
      - 1
    - 1: predicted.height
      5: 1
      6:
      - 1
    - 1: label._type
      5: 1
      6:
      - 1
    - 1: label.path
      5: 1
      6:
      - 1
    - 1: label.sha256
      5: 1
      6:
      - 1
    - 1: label.size
      5: 1
      6:
      - 1
    - 1: label.format
      5: 1
      6:
      - 1
    - 1: label.width
      5: 1
      6:
      - 1
    - 1: label.height
      5: 1
      6:
      - 1
    - 1: Normalized_val_loss
      5: 1
      6:
      - 1
    - 1: Precision
      5: 1
      6:
      - 1
    - 1: Recall
      5: 1
      6:
      - 1
    - 1: F1 score
      5: 1
      6:
      - 1
    - 1: Average number of detected_points
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    python_version: 3.8.5
    start_time: 1651067112
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      4: 3.8.5
      5: 0.12.14
      8:
      - 5
