#!/bin/bash

echo 'Deleting old dataset and generating with new ULM image'

rm -f ./data/train_images/images_ULM/*.png
rm -f ./data/train_images/ULM_points/*.mat

rm -f ./data/val_images/images_ULM/*.png
rm -f ./data/val_images/ULM_points/*.mat

python3 ./utils/csv_manip.py