#!/bin/bash

echo 'Deleting old dataset and generating with new IOSTAR and DRIVE images'

rm -f ./data_IOSTAR/train_images/images_IOSTAR/*.png
rm -f ./data_IOSTAR/train_images/IOSTAR_points/*.mat

rm -f ./data_IOSTAR/val_images/images_IOSTAR/*.png
rm -f ./data_IOSTAR/val_images/IOSTAR_points/*.mat

python3 ./utils/csv_manip_IOSTAR.py