wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1708523723
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
alpha:
  desc: null
  value: 0.5
beta:
  desc: null
  value: 0.1
decalage:
  desc: null
  value: 0
eps:
  desc: null
  value: 0.1
sigma:
  desc: null
  value: 0.1
threshold_metric:
  desc: null
  value: 0.2
threshold_tree:
  desc: null
  value: 0.05
xi:
  desc: null
  value: 1.0
