wandb_version: 1

alpha:
  value: 6.605596018036414
batch_size:
  value: 16
features:
  value: 8
lr:
  value: 2.2904708745941123e-05
out_channels:
  value: 4
patience:
  value: 50
size:
  value: 256
vesselnet:
  value: false
